[platformio]
src_dir = main

[env:waveshare-knob]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = espidf
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
build_flags =
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DLV_COLOR_DEPTH=16
    -O3
    -funroll-loops
